package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	model "go-graphql/app/models"
)

// CreateAnswer is the resolver for the CreateAnswer field.
func (r *mutationResolver) CreateAnswer(ctx context.Context, questionID string, optionID string) (*model.AnswerResponse, error) {
	panic(fmt.Errorf("not implemented: CreateAnswer - CreateAnswer"))
}

// UpdateAnswer is the resolver for the UpdateAnswer field.
func (r *mutationResolver) UpdateAnswer(ctx context.Context, id string, questionID string, optionID string) (*model.AnswerResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateAnswer - UpdateAnswer"))
}

// DeleteAnswer is the resolver for the DeleteAnswer field.
func (r *mutationResolver) DeleteAnswer(ctx context.Context, id string) (*model.AnswerResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteAnswer - DeleteAnswer"))
}

// GetOneAnswer is the resolver for the GetOneAnswer field.
func (r *queryResolver) GetOneAnswer(ctx context.Context, id string) (*model.AnswerResponse, error) {
	panic(fmt.Errorf("not implemented: GetOneAnswer - GetOneAnswer"))
}

// GetAllQuestionAnswers is the resolver for the GetAllQuestionAnswers field.
func (r *queryResolver) GetAllQuestionAnswers(ctx context.Context, questionID string) (*model.AnswerResponse, error) {
	panic(fmt.Errorf("not implemented: GetAllQuestionAnswers - GetAllQuestionAnswers"))
}
